### ISSUE TITLE
Tried with arduino Nano but input is 1sec lag

### ISSUE THREAD

**Issue by NagaRavi259** [fahrvergnuugen/rc-differential-thrust-mixer#2]
I tried your code with Arduino Nano & it works motor functions but it lag when i give input to it 
After giving input it wait sec & start motor & when i release the throttle it stop after 1sec

**Comment by ghost** [comment]
Hello, I am thinking about using this code for a similar case.
Did you ever find out why it behaves like that with the arduino? Do you think it could work with just a simple AVR microcontroller?

**Comment by PaulWieland** [comment]
I won't have time to figure out why the Arduino is slow. I will say that it worked just fine with a Teensy 3.2.

**Comment by NagaRavi259** [comment]
I got it working & i modified to use potentiometer input with tether cable 
It was used for controlling ROV in under water 2.4ghz won't work and some 75Mhz & 47Mhz controllers are costly so I'm using tether cable
Lucfer1501 if u thinking to use...! the code needs PWM input if you have controller that generate PWM signel it works fine
